# Project: pestRoutesAPI

class table:
    tables = {
        "Contract" : {
            "urlEndpoint" : "contract",
            "sqlPK" : "contractIDs",
            "queryPlural" : "contractIDs",
            "sqlTable" : "PR.Contract",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/contract/search?authenticationKey={}&authenticationToken={}&dateSigned={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/contract/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/contract/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "contractIDs",
            "dateBool" : True,
            "dataPlural" : "contracts",
            "idList" : [],
            "dataList": []
        },
        "Appointment" : {
            "urlEndpoint" : "appointment",
            "sqlPK" : "appointmentID",
            "queryPlural" : "appointmentIDs",
            "sqlTable" : "PR.Appointment",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/appointment/search?authenticationKey={}&authenticationToken={}&dateAdded={}&status={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/appointment/search?authenticationKey={}&authenticationToken={}&dateUpdated={}&status={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/appointment/get?authenticationKey={}&authenticationToken={}&includeCancellationReason=1&includeTargetPests=1&includeCustomFields=1",
            "payloadKey" : "appointmentIDs",
            "dateBool" : True,
            "dataPlural" : "appointments",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "AppointmentReminder" : {
            "urlEndpoint" : "appointmentReminder",
            "sqlPK" : "reminderID",
            "queryPlural" : "appointmentReminderIDs",
            "sqlTable" : "PR.AppointmentReminder",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/appointmentReminder/search?authenticationKey={}&authenticationToken={}&dateSent={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/appointmentReminder/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/appointmentReminder/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "reminderIDs",
            "dateBool" : True,
            "dataPlural" : "appointmentReminders",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "CustomerFlag" : {
            "urlEndpoint" : "customerFlag",
            "sqlPK" : "customerID",
            "queryPlural" : "customerIDs",
            "sqlTable" : "PR.CustomerFlag",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/customerFlag/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/customerFlag/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "customerIDs",
            "dateBool" : False,
            "dataPlural" : "customerFlags",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Document" : {
            "urlEndpoint" : "document",
            "sqlPK" : "uploadID",
            "queryPlural" : "documentIDs",
            "sqlTable" : "PR.Document",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/document/search?authenticationKey={}&authenticationToken={}&dateAdded={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/document/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/document/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "uploadIDs",
            "dateBool" : True,
            "dataPlural" : "documents",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Customer" : {
            "urlEndpoint" : "customer",
            "sqlPK" : "customerID",
            "queryPlural" : "customerIDs",
            "sqlTable" : "PR.Customer",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/customer/search?authenticationKey={}&authenticationToken={}&dateAdded={}&active{}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/customer/search?authenticationKey={}&authenticationToken={}&dateUpdated={}&active{}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/customer/get?authenticationKey={}&authenticationToken={}&includeCustomerFlag=1",
            "payloadKey" : "customerIDs",
            "dateBool" : True,
            "dataPlural" : "customers",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Employee" : {
            "urlEndpoint" : "employee",
            "sqlPK" : "employeeID",
            "queryPlural" : "employeeIDs",
            "sqlTable" : "PR.Employee",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/employee/search?authenticationKey={}&authenticationToken={}&active={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/employee/search?authenticationKey={}&authenticationToken={}&dateUpdated={}&active={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/employee/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "employeeIDs",
            "dateBool" : False,
            "dataPlural" : "employees",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Office" : {
            "urlEndpoint" : "office",
            "sqlPK" : "officeID",
            "queryPlural" : "officeIDs",
            "sqlTable" : "PR.Office",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/office/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/office/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "officeIDs",
            "dateBool" : False,
            "dataPlural" : "offices",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Payment" : {
            "urlEndpoint" : "payment",
            "sqlPK" : "paymentID",
            "queryPlural" : "paymentIDs",
            "sqlTable" : "PR.Payment",
            "stagingTable" : "StagingPayment",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/payment/search?authenticationKey={}&authenticationToken={}&date={}&status={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/payment/search?authenticationKey={}&authenticationToken={}&dateUpdated={}&status={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/payment/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "paymentIDs",
            "dateBool" : True,
            "dataPlural" : "payments",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "PaymentApplication" : {
            "urlEndpoint" : "appliedPayment",
            "sqlPK" : "appliedPaymentID",
            "queryPlural" : "appliedPaymentIDs",
            "sqlTable" : "PR.PaymentApplicationNew",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/appliedPayment/search?authenticationKey={}&authenticationToken={}&dateApplied={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/appliedPayment/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/appliedPayment/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "appliedPaymentIDs",
            "dateBool" : True,
            "dataPlural" : "appliedPayments",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "ServiceType" : {
            "urlEndpoint" : "servicetype",
            "sqlPK" : "typeID",
            "queryPlural" : "serviceTypeIDs",
            "sqlTable" : "PR.ServiceType",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/serviceType/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/serviceType/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "typeIDs",
            "dateBool" : False,
            "dataPlural" : "serviceTypes",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Subscription" : {
            "urlEndpoint" : "subscription",
            "sqlPK" : "subscriptionID",
            "queryPlural" : "subscriptionIDs",
            "sqlTable" : "PR.Subscription",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/subscription/search?authenticationKey={}&authenticationToken={}&dateAdded={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/subscription/search?authenticationKey={}&authenticationToken={}&dateUpdated={}&active={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/subscription/get?authenticationKey={}&authenticationToken={}&includeCancellationReason=1",
            "payloadKey" : "subscriptionIDs",
            "dateBool" : True,
            "dataPlural" : "subscriptions",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Lead" : {
            "urlEndpoint" : "subscription",
            "sqlPK" : "subscriptionID",
            "queryPlural" : "subscriptionIDs",
            "sqlTable" : "PR.Subscription",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/subscription/search?authenticationKey={}&authenticationToken={}&leadDateAdded={}{}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/subscription/search?authenticationKey={}&authenticationToken={}&leadUpdated={}{}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/subscription/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "subscriptionIDs",
            "dateBool" : True,
            "dataPlural" : "subscriptions",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Ticket" : {
            "urlEndpoint" : "ticket",
            "sqlPK" : "ticketID",
            "queryPlural" : "ticketIDs",
            "sqlTable" : "PR.Ticket",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/ticket/search?authenticationKey={}&authenticationToken={}&dateCreated={}&status{}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/ticket/search?authenticationKey={}&authenticationToken={}&dateUpdated={}&status{}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/ticket/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "ticketIDs",
            "dateBool" : True,
            "dataPlural" : "tickets",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Form" : {
            "urlEndpoint" : "form",
            "sqlPK" : "formID",
            "queryPlural" : "formIDs",
            "sqlTable" : "PR.Form",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/form/search?authenticationKey={}&authenticationToken={}&dateAdded={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/form/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "contractIDs",
            "dateBool" : True,
            "dataPlural" : "forms",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Knock" : {
            "urlEndpoint" : "knock",
            "sqlPK" : "knockID",
            "queryPlural" : "knockIDs",
            "sqlTable" : "PR.Knock",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/knock/search?authenticationKey={}&authenticationToken={}&dateAdded={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/knock/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "knockIDs",
            "dateBool" : True,
            "dataPlural" : "knocks",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "AccessControl" : {
            "urlEndpoint" : "accessControl",
            "sqlPK" : "employeeID",
            "queryPlural" : "employeeIDs",
            "sqlTable" : "PR.AccessProfile",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/employee/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/accessControl/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "employeeIDs",
            "dateBool" : False,
            "dataPlural" : "accessControls",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "GenericFlag" : {
            "urlEndpoint" : "genericFlag",
            "sqlPK" : "genericFlagID",
            "queryPlural" : "genericFlagIDs",
            "sqlTable" : "PR.GenericFlag",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/genericFlag/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/genericFlag/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "genericFlagIDs",
            "dateBool" : False,
            "dataPlural" : "genericFlags",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "GenericFlagAssignment" : {
            "urlEndpoint" : "genericFlagAssignment",
            "sqlPK" : "genericFlagAssignmentID",
            "queryPlural" : "genericFlagAssignmentIDs",
            "sqlTable" : "PR.GenericFlagAssignment",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/genericFlagAssignment/search?authenticationKey={}&authenticationToken={}&dateCreated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/genericFlagAssignment/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/genericFlagAssignment/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "genericFlagAssignmentIDs",
            "dateBool" : True,
            "dataPlural" : "genericFlagAssignments",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Note" : {
            "urlEndpoint" : "note",
            "sqlPK" : "noteID",
            "queryPlural" : "noteIDs",
            "sqlTable" : "PR.Note",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/note/search?authenticationKey={}&authenticationToken={}&dateAdded={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/note/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/note/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "noteIDs",
            "dateBool" : True,
            "dataPlural" : "notes",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "PaymentProfile" : {
            "urlEndpoint" : "paymentProfile",
            "sqlPK" : "paymentProfileID",
            "queryPlural" : "paymentProfileIDs",
            "sqlTable" : "PR.PaymentProfile",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/paymentProfile/search?authenticationKey={}&authenticationToken={}&dateCreated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/paymentProfile/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/paymentProfile/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "paymentProfileIDs",
            "dateBool" : True,
            "dataPlural" : "paymentProfiles",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Product" : {
            "urlEndpoint" : "product",
            "sqlPK" : "productID",
            "queryPlural" : "productIDs",
            "sqlTable" : "PR.Product",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/product/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/product/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "productIDs",
            "dateBool" : False,
            "dataPlural" : "products",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Region" : {
            "urlEndpoint" : "region",
            "sqlPK" : "regionIDs",
            "queryPlural" : "regionIDs",
            "sqlTable" : "PR.Region",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/region/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/region/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "regionIDs",
            "dateBool" : False,
            "dataPlural" : "regions",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Review" : {
            "urlEndpoint" : "review",
            "sqlPK" : "feedbackID",
            "queryPlural" : "reviewIDs",
            "sqlTable" : "PR.Review",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/review/search?authenticationKey={}&authenticationToken={}&date={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/review/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "feedbackIDs",
            "dateBool" : True,
            "dataPlural" : "reviews",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Route" : {
            "urlEndpoint" : "route",
            "sqlPK" : "routeID",
            "queryPlural" : "routeIDs",
            "sqlTable" : "PR.Route",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/route/search?authenticationKey={}&authenticationToken={}&date={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/route/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/route/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "routeIDs",
            "dateBool" : True,
            "dataPlural" : "routes",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        # "Spot" : {
        #   "urlEndpoint" : "spot",
        #   "sqlPK" : "spotID",
        #   "queryPlural" : "spotIDs",
        #   "sqlTable" : "PR.Spot",
        #   "getIdUrl" : "https://moxie{}.pestroutes.com/api/spot/search?authenticationKey={}&authenticationToken={}&date={}",
        #   "bulkUrl" : "https://moxie{}.pestroutes.com/api/spot/get?authenticationKey={}&authenticationToken={}&spotIDs={}",
        #   "dateBool" : True,
        #   "dataPlural" : "spots",
        #   "removeKeys" : ["unitIDs"],
        #   "idList" : [],
        # "dataList": [],
        # "dataList": []
        # },
        "Task" : {
            "urlEndpoint" : "task",
            "sqlPK" : "taskIDs",
            "queryPlural" : "taskIDs",
            "sqlTable" : "PR.Task",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/task/search?authenticationKey={}&authenticationToken={}&dateAdded={}&status={}&type={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/task/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/task/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "taskIDs",
            "dateBool" : True,
            "dataPlural" : "tasks",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Changelog" : {
            "urlEndpoint" : "changelog",
            "sqlPK" : "changeID",
            "queryPlural" : "changelogIDs",
            "sqlTable" : "PR.Changelog",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/changelog/search?authenticationKey={}&authenticationToken={}&dateChanged={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/changelog/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "changeIDs",
            "dateBool" : True,
            "dataPlural" : "changelogs",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "TimeClock" : {
            "urlEndpoint" : "timeClock",
            "sqlPK" : "entryID",
            "queryPlural" : "timeClockIDs",
            "sqlTable" : "PR.TimeClock",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/timeClock/search?authenticationKey={}&authenticationToken={}&timeIn={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/timeClock/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "entryIDs",
            "dateBool" : True,
            "dataPlural" : "timeClocks",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "TimeClockCategory" : {
            "urlEndpoint" : "timeClockCategory",
            "sqlPK" : "clockCategoryID",
            "queryPlural" : "timeClockCategoryIDs",
            "sqlTable" : "PR.TimeClockCategory",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/timeClockCategory/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/timeClockCategory/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "clockCategoryIDs",
            "dateBool" : False,
            "dataPlural" : "timeClockCategorys",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Unit" : {
            "urlEndpoint" : "unit",
            "sqlPK" : "unitID",
            "queryPlural" : "unitIDs",
            "sqlTable" : "PR.Unit",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/unit/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/unit/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "unitIDs",
            "dateBool" : False,
            "dataPlural" : "units",
            "removeKeys" : ["unitIDs"],
            "idList" : [],
            "dataList": []
        },
        "Team" : {
            "urlEndpoint" : "team",
            "sqlPK" : "teamID",
            "queryPlural" : "teamIDs",
            "sqlTable" : "PR.Team",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/team/search?authenticationKey={}&authenticationToken={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/team/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "teamIDs",
            "dateBool" : False,
            "dataPlural" : "teams",
            "removeKeys" : ["teamIDs"],
            "idList" : [],
            "dataList": []
        },
        "Door" : {
            "urlEndpoint" : "door",
            "sqlPK" : "doorID",
            "queryPlural" : "doorIDs",
            "sqlTable" : "PR.Door",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/door/search?authenticationKey={}&authenticationToken={}&dateAdded={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/door/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "doorIDs",
            "dateBool" : True,
            "dataPlural" : "doors",
            "removeKeys" : ["doorIDs"],
            "idList" : [],
            "dataList": []
        },
        "Chemical" : {
            "urlEndpoint" : "chemical",
            "sqlPK" : "chemicalID",
            "queryPlural" : "chemicalIDs",
            "sqlTable" : "PR.Chemical",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/chemical/search?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/chemical/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/chemical/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "chemicalIDs",
            "dateBool" : False,
            "dataPlural" : "chemicals",
            "removeKeys" : ["chemicalIDs"],
            "idList" : [],
            "dataList": []
        },
        "ChemicalUse" : {
            "urlEndpoint" : "chemicalUse",
            "sqlPK" : "chemicalUseID",
            "queryPlural" : "chemicalUseIDs",
            "sqlTable" : "PR.ChemicalUse",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/chemicalUse/search?authenticationKey={}&authenticationToken={}&dateCreated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/chemicalUse/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/chemicalUse/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "chemicalUseIDs",
            "dateBool" : True,
            "dataPlural" : "chemicalUses",
            "removeKeys" : ["chemicalUseIDs"],
            "idList" : [],
            "dataList": []
        },
        "Diagram" : {
            "urlEndpoint" : "diagram",
            "sqlPK" : "diagram",
            "queryPlural" : "diagramIDs",
            "sqlTable" : "PR.Diagram",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/diagram/search?authenticationKey={}&authenticationToken={}&dateCreated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/diagram/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/diagram/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "diagramIDs",
            "dateBool" : True,
            "dataPlural" : "diagrams",
            "removeKeys" : ["diagramIDs"],
            "idList" : [],
            "dataList": []
        },
        "Disbursement" : {
            "urlEndpoint" : "disbursement",
            "sqlPK" : "gatewayDisbursementID",
            "queryPlural" : "disbursementIDs",
            "sqlTable" : "PR.Disbursement",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/disbursement/search?authenticationKey={}&authenticationToken={}&dateCreated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/disbursement/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/disbursement/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "gatewayDisbursementIDs",
            "dateBool" : True,
            "dataPlural" : "disbursements",
            "removeKeys" : ["gatewayDisbursementIDs"],
            "idList" : [],
            "dataList": []
        },
        "DisbursementItem" : {
            "urlEndpoint" : "disbursementItem",
            "sqlPK" : "gatewayDisbursementEntryID",
            "queryPlural" : "disbursementItemIDs",
            "sqlTable" : "PR.DisbursementItem",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/disbursementItem/search?authenticationKey={}&authenticationToken={}&dateCreated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/disbursementItem/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/disbursementItem/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "gatewayDisbursementEntryIDs",
            "dateBool" : True,
            "dataPlural" : "disbursementItems",
            "removeKeys" : ["gatewayDisbursementEntryIDs"],
            "idList" : [],
            "dataList": []
        },
        "Group" : {
            "urlEndpoint" : "group",
            "sqlPK" : "groupID",
            "queryPlural" : "groupIDs",
            "sqlTable" : "PR.Group",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/group/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/group/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/group/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "groupIDs",
            "dateBool" : True,
            "dataPlural" : "groups",
            "removeKeys" : ["groupIDs"],
            "idList" : [],
            "dataList": []
        },
        "Spot" : {
            "urlEndpoint" : "spot",
            "sqlPK" : "spotID",
            "queryPlural" : "spotIDs",
            "sqlTable" : "PR.Spot",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/spot/search?authenticationKey={}&authenticationToken={}&date={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/spot/get?authenticationKey={}&authenticationToken={}",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/spot/search?authenticationKey={}&authenticationToken={}&dateUpdated={}",
            "payloadKey" : "spotIDs",
            "dateBool" : True,
            "dataPlural" : "spots",
            "removeKeys" : ["spotIDs"],
            "idList" : [],
            "dataList": []
        },
        "Insect" : {
            "urlEndpoint" : "insect",
            "sqlPK" : "insectID",
            "queryPlural" : "insectIDs",
            "sqlTable" : "PR.Insect",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/insect/search?authenticationKey={}&authenticationToken={}&date={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/insect/get?authenticationKey={}&authenticationToken={}",
            "payloadKey" : "insectIDs",
            "dateBool" : True,
            "dataPlural" : "insects",
            "removeKeys" : ["insectIDs"],
            "idList" : [],
            "dataList": []
        },
        "ServicePlan" : {
            "urlEndpoint" : "servicePlan",
            "sqlPK" : "subscriptionID",
            "queryPlural" : "servicePlanIDs",
            "sqlTable" : "PR.ServicePlan",
            "getIdUrl" : "https://moxie{}.pestroutes.com/api/servicePlan/search?authenticationKey={}&authenticationToken={}&dateAdded={}&active={}",
            "bulkUrl" : "https://moxie{}.pestroutes.com/api/servicePlan/get?authenticationKey={}&authenticationToken={}&includeCancellationReason=1",
            "dateUpdate" : "https://moxie{}.pestroutes.com/api/servicePlan/search?authenticationKey={}&authenticationToken={}&dateUpdated={}&active={}",
            "payloadKey" : "subscriptionIDs",
            "dateBool" : True,
            "dataPlural" : "servicePlans",
            "removeKeys" : ["subscriptionIDs"],
            "idList" : [],
            "dataList": []
        }
    }      
